name: Version

on:
  pull_request:
    types: [ closed ]
    branches: [ develop ]
  push:
    branches: [ develop ]
  
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Git configure
        run: |
          git config --global user.email "git-bot@crn-software.fr"
          git config --global user.name "CRN Software"
          git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/Plokkke/github-actions-tests.git

      - name: Semantic Release - Version
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          semantic_version: 19.0.2
          dry_run: true
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set version
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}
          npm version ${{ steps.semantic.outputs.new_release_version }} --no-git-tag-version

      - name: Commit and Push
        run: |
          git add .
          git commit --amend --no-edit
          git push origin develop
          git tag v${{ steps.semantic.outputs.new_release_version }}
          git push --tags