name: Version

on:
  push:
    branches: [ develop ]
  
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Git configure
        run: |
          git config --global user.email "git-bot@crn-software.fr"
          git config --global user.name "CRN Software"

      - name: Semantic Release Config
        run: |
          echo '{
                  "branches": "develop",
                  "dry_run": true,
                  "plugins": [
                    "@semantic-release/commit-analyzer"
                  ]
                }
          '> .releaserc
      - name: Semantic Release
        run: npx --no-install semantic-release --no-ci --dry-run

      - name: Get version
        run: npx --no-install semantic-release --no-ci --dry-run | grep -oP 'The next release version is \K[0-9]+\.[0-9]+\.[0-9]+'

      - name: Output version
        id: semantic
        run: echo "version=$(npx --no-install semantic-release --no-ci --dry-run | grep -oP 'The next release version is \K[0-9]+\.[0-9]+\.[0-9]+')" >> "$GITHUB_OUTPUT"

      - name: Set version
        if: steps.semantic.outputs.version != ''
        run: |
          npm version ${{ steps.semantic.outputs.version }} --no-git-tag-version

      - name: Commit and Push
        if: steps.semantic.outputs.version != ''
        run: |
          git add package.json package-lock.json
          git commit --amend --no-edit
          git tag v${{ steps.semantic.outputs.new_release_version }}
          git push --force origin develop
          git push --tags