name: Version

on:
  pull_request:
    types: [ closed ]
    branches: [ develop ]
  
jobs:
  update-version:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Git configure
        run: |
          git config --global user.email "git-bot@crn-software.fr"
          git config --global user.name "CRN Software"
          git remote set-url origin https://${{ secrets.ACCESS_TOKEN }}@github.com/Plokkke/github-actions-tests.git
          git fetch --all
          git checkout develop

      - name: Semantic Release Config - Version
        run: |
          echo '{
                   "tagFormat":"${version}",
                   "plugins": [
                      "@semantic-release/commit-analyzer",
                      "@semantic-release/github"
                   ]
                }
          '> .releaserc

      - name: Semantic Release - Version
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          semantic_version: 19.0.5 
          extra_plugins: |
            @semantic-release/commit-analyzer@9.0.2
            @semantic-release/github@8.0.2
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set version
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}
          npm version ${{ steps.semantic.outputs.new_release_version }} --no-git-tag-version

      - name: Commit and Push
        run: |
          git add .
          git commit --amend --no-edit
          git push --force origin develop
          git tag v${{ steps.semantic.outputs.new_release_version }}
          git push --tags