name: Version

on:
  push:
    branches: [ develop ]
  
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Git configure
        run: |
          git config --global user.email "git-bot@crn-software.fr"
          git config --global user.name "CRN Software"
          git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/Plokkke/github-actions-tests.git

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          semantic_version: 19.0.2
          branches: 'develop'
          dry_run: true
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/github
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Set version
        if: steps.semantic.outputs.new_release_version != ''
        run: |
          npm version ${{ steps.semantic.outputs.new_release_version }} --no-git-tag-version

      - name: Commit and Push
        if: steps.semantic.outputs.new_release_version != ''
        run: |
          git add package.json package-lock.json
          git commit --amend --no-edit
          git tag v${{ steps.semantic.outputs.new_release_version }}
          git push --force origin develop
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}